/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;
import model.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;

/**
 *
 * @author USER
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    /**
     * Creates new form CreatePersonJPanel
     */
    CreatePersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnCreatePerson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtWorkStreet = new javax.swing.JTextField();
        txtWorkUnit = new javax.swing.JTextField();
        txtWorkCity = new javax.swing.JTextField();
        txtWorkState = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtWorkZip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtWorkPhoneNumber = new javax.swing.JTextField();
        HomeAddress = new javax.swing.JPanel();
        txtHomeStreet = new javax.swing.JTextField();
        txtHomeUnit = new javax.swing.JTextField();
        txtHomeCity = new javax.swing.JTextField();
        txtHomeState = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtHomeZip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHomePhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Create Person");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 774, -1));

        txtFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, 30));

        txtLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 161, 30));

        txtSSN.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 170, 30));

        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 161, 30));

        btnCreatePerson.setBackground(new java.awt.Color(255, 255, 153));
        btnCreatePerson.setForeground(new java.awt.Color(0, 0, 51));
        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });
        add(btnCreatePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 473, 170, 30));

        jLabel1.setText("First Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, 30));

        jLabel2.setText("Last Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 66, -1, 30));

        jLabel3.setText("Social Security Number:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 66, -1, 30));

        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Work address"));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWorkStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkStreetActionPerformed(evt);
            }
        });
        jPanel3.add(txtWorkStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 39, 144, -1));
        jPanel3.add(txtWorkUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 39, 134, -1));
        jPanel3.add(txtWorkCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 95, 144, -1));

        txtWorkState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkStateActionPerformed(evt);
            }
        });
        jPanel3.add(txtWorkState, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, 134, -1));

        jLabel13.setText("Street Address");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 18, 89, -1));

        jLabel18.setText("Unit Number");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 18, 80, -1));

        jLabel19.setText("City");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 73, 37, -1));

        jLabel20.setText("State");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 73, 37, -1));

        jLabel21.setText("Zip code");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtWorkZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkZipActionPerformed(evt);
            }
        });
        jPanel3.add(txtWorkZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 144, -1));

        jLabel10.setText("Phone Number");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        jPanel3.add(txtWorkPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 380, 200));

        HomeAddress.setBackground(new java.awt.Color(204, 204, 204));
        HomeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Home Address"));
        HomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        HomeAddress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        HomeAddress.add(txtHomeStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 39, 144, -1));
        HomeAddress.add(txtHomeUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 39, 134, -1));
        HomeAddress.add(txtHomeCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 95, 144, -1));
        HomeAddress.add(txtHomeState, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, 134, -1));

        jLabel6.setText("Street Address");
        HomeAddress.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 18, 89, -1));

        jLabel7.setText("Unit Number");
        HomeAddress.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 18, 80, -1));

        jLabel8.setText("City");
        HomeAddress.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 73, 37, -1));

        jLabel9.setText("State");
        HomeAddress.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 73, 37, -1));

        jLabel22.setText("Zip code");
        HomeAddress.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 64, -1));
        HomeAddress.add(txtHomeZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 144, -1));

        jLabel11.setText("Phone Number");
        HomeAddress.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        HomeAddress.add(txtHomePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, -1));

        add(HomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 363, 200));

        jLabel5.setText("Height");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, 30));
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        int ssnNew,workZipNew,homeZipNew,ageNew;
        double heightNew;
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String ssn = txtSSN.getText();
        String age = txtAge.getText();
        String height = txtHeight.getText();
        
        String workStreet = txtWorkStreet.getText();
        String workUnit = txtWorkUnit.getText();
        String workCity = txtWorkCity.getText();
        String workState = txtWorkState.getText();
        String workZip = txtWorkZip.getText();
        String workPhone = txtWorkPhoneNumber.getText();
        
        String homeStreet = txtHomeStreet.getText();
        String homeUnit = txtHomeUnit.getText();
        String homeCity = txtHomeCity.getText();
        String homeState = txtHomeState.getText();
        String homeZip = txtHomeZip.getText();
        String homePhone = txtHomePhoneNumber.getText();

        if ("".equals(firstName) || "".equals(lastName)||"".equals(height) || "".equals(age) || "".equals(ssn)
                || "".equals(workStreet)||"".equals(workPhone) || "".equals(workUnit) || "".equals(workCity) || "".equals(workState) || "".equals(workZip) 
                || "".equals(homeStreet) || "".equals(homeUnit) || "".equals(homeCity) || "".equals(homeState) || "".equals(homeZip)||"".equals(homePhone)) {
            JOptionPane.showMessageDialog(null, "Please enter all the details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        /*Parsing for SSN*/
        try {
            ssnNew = Integer.parseInt(ssn);
            if (ssnNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric SSN!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
       
        /*Parsing for WZip*/
        try {
            workZipNew = Integer.parseInt(workZip);
            if (workZipNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric zip code!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
         /*Parsing for HZip*/
        try {
            homeZipNew = Integer.parseInt(homeZip);
            if (homeZipNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric zip code!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         /*Parsing for age*/
        try {
            ageNew = Integer.parseInt(age);
            if (ageNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a age!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        /*Parsing for height*/
       try {
            heightNew = Double.parseDouble(height);
            if (heightNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric SSN!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Person person = personDirectory.addPerson();
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setSsn(ssnNew);
        person.setAge(ageNew);
        person.setHeight(heightNew);
        
        Address workAddress = new Address();
        Address homeAddress = new Address();
        
        workAddress.setStreetAddress(workStreet);
        workAddress.setUnitNumber(workUnit);
        workAddress.setCity(workCity);
        workAddress.setState(workState);
        workAddress.setZip(workZipNew);
        workAddress.setPhoneNumber(Long.parseLong(workPhone));
        person.setWorkAddress(workAddress);
        
        homeAddress.setStreetAddress(homeStreet);
        homeAddress.setUnitNumber(homeUnit);
        homeAddress.setCity(homeCity);
        homeAddress.setState(homeState);
        homeAddress.setPhoneNumber(Long.parseLong(homePhone));
        homeAddress.setZip(homeZipNew);
        
        person.setHomeAddress(homeAddress);

        JOptionPane.showMessageDialog(null, "Person successfully created");

        txtFirstName.setText("");
        txtLastName.setText("");
        txtSSN.setText("");
        txtAge.setText("");
        txtHeight.setText("");
        
        txtWorkStreet.setText("");
        txtWorkUnit.setText("");
        txtWorkCity.setText("");
        txtWorkState.setText("");
        txtWorkZip.setText("");
        txtWorkPhoneNumber.setText("");
        
        txtHomeStreet.setText("");
        txtHomeUnit.setText("");
        txtHomeCity.setText("");
        txtHomeState.setText("");
        txtHomeZip.setText("");
        txtHomePhoneNumber.setText("");
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void txtWorkStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkStreetActionPerformed

    private void txtWorkStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkStateActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtWorkZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkZipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeAddress;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomePhoneNumber;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeStreet;
    private javax.swing.JTextField txtHomeUnit;
    private javax.swing.JTextField txtHomeZip;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkPhoneNumber;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreet;
    private javax.swing.JTextField txtWorkUnit;
    private javax.swing.JTextField txtWorkZip;
    // End of variables declaration//GEN-END:variables
}
