/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;

/**
 *
 * @author USER
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Person person;
    private Address workAddress;
    private Address homeAddress;
    /**
     * Creates new form ViewAccountJPanel
     */
    ViewPersonJPanel(JPanel userProcessContainer, Person person, Address workAddress, Address homeAddress) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.workAddress = workAddress;
        this.homeAddress = homeAddress;
        populateAccountDetails();
        
        
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void populateAccountDetails() {
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSSN.setText(Long.toString(person.getSsn()));
        txtAge.setText(Integer.toString(person.getAge()));
        txtHeight.setText(Double.toString(person.getHeight()));
        
        txtWorkStreet.setText(workAddress.getStreetAddress());
        txtWorkUnit.setText(workAddress.getUnitNumber());
        txtWorkCity.setText(workAddress.getCity());
        txtWorkState.setText(workAddress.getState());
        txtWorkZip.setText(Integer.toString(workAddress.getZip()));
        txtWorkPhoneNumber.setText(Long.toString(workAddress.getPhoneNumber()));
        
        txtHomeStreet.setText(homeAddress.getStreetAddress());
        txtHomeUnit.setText(homeAddress.getUnitNumber());
        txtHomeCity.setText(homeAddress.getCity());
        txtHomeState.setText(homeAddress.getState());
        txtHomeZip.setText(Integer.toString(homeAddress.getZip()));
        txtHomePhoneNumber.setText(Long.toString(homeAddress.getPhoneNumber()));
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtWorkStreet = new javax.swing.JTextField();
        txtWorkUnit = new javax.swing.JTextField();
        txtWorkCity = new javax.swing.JTextField();
        txtWorkState = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtWorkZip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWorkPhoneNumber = new javax.swing.JTextField();
        HomeAddress = new javax.swing.JPanel();
        txtHomeStreet = new javax.swing.JTextField();
        txtHomeUnit = new javax.swing.JTextField();
        txtHomeCity = new javax.swing.JTextField();
        txtHomeState = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtHomeZip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHomePhoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblHeader.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(51, 0, 51));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("View Person");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 407, 24));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 450, 130, 35));

        btnUpdate.setForeground(new java.awt.Color(0, 0, 51));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 130, 35));

        lblFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblFirstName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 51, 51));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("First Name:");
        lblFirstName.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        lblLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblLastName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 51, 51));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name:");
        lblLastName.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 70, 30));

        lblSSN.setBackground(new java.awt.Color(255, 255, 255));
        lblSSN.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(0, 51, 51));
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSSN.setText("Social Security Number:");
        lblSSN.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 134, -1));

        lblLicenseNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblLicenseNumber.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblLicenseNumber.setForeground(new java.awt.Color(0, 51, 51));
        lblLicenseNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLicenseNumber.setText("Age");
        lblLicenseNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 99, -1));

        txtFirstName.setBackground(new java.awt.Color(204, 204, 204));
        txtFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFirstName.setEnabled(false);
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 30));

        txtLastName.setBackground(new java.awt.Color(204, 204, 204));
        txtLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLastName.setEnabled(false);
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 170, 30));

        txtSSN.setBackground(new java.awt.Color(204, 204, 204));
        txtSSN.setForeground(new java.awt.Color(255, 255, 255));
        txtSSN.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSSN.setEnabled(false);
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 170, 30));

        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAge.setEnabled(false);
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Work address"));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWorkStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkStreetActionPerformed(evt);
            }
        });
        jPanel3.add(txtWorkStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 39, 144, -1));
        jPanel3.add(txtWorkUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 39, 134, -1));
        jPanel3.add(txtWorkCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 95, 144, -1));
        jPanel3.add(txtWorkState, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 95, 134, -1));

        jLabel13.setText("Street Address");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 18, 89, -1));

        jLabel18.setText("Unit Number");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 18, 80, -1));

        jLabel19.setText("City");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 73, 37, -1));

        jLabel20.setText("State");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 73, 37, -1));

        jLabel21.setText("Zip code");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel3.add(txtWorkZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 144, -1));

        jLabel2.setText("Phone Number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));
        jPanel3.add(txtWorkPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 407, 200));

        HomeAddress.setBackground(new java.awt.Color(204, 204, 204));
        HomeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Home Address"));
        HomeAddress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        HomeAddress.add(txtHomeStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 39, 144, -1));
        HomeAddress.add(txtHomeUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 39, 134, -1));
        HomeAddress.add(txtHomeCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 95, 144, -1));
        HomeAddress.add(txtHomeState, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 95, 134, -1));

        jLabel6.setText("Street Address");
        HomeAddress.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 18, 89, -1));

        jLabel7.setText("Unit Number");
        HomeAddress.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 18, 80, -1));

        jLabel8.setText("City");
        HomeAddress.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 73, 37, -1));

        jLabel9.setText("State");
        HomeAddress.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 73, 37, -1));

        jLabel22.setText("Zip code");
        HomeAddress.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 143, 76, -1));
        HomeAddress.add(txtHomeZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 165, 144, -1));

        jLabel3.setText("Phone Number");
        HomeAddress.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 80, -1));
        HomeAddress.add(txtHomePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, -1));

        add(HomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 350, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Height");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 50, 30));

        txtHeight.setBackground(new java.awt.Color(204, 204, 204));
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtAge.setEnabled(true);
        txtHeight.setEnabled(true);
        
        txtWorkStreet.setEnabled(true);
        txtWorkUnit.setEnabled(true);
        txtWorkCity.setEnabled(true);
        txtWorkState.setEnabled(true);
        txtWorkZip.setEnabled(true);
        txtWorkPhoneNumber.setEnabled(true);
        
        txtHomeStreet.setEnabled(true);
        txtHomeUnit.setEnabled(true);
        txtHomeCity.setEnabled(true);
        txtHomeState.setEnabled(true);
        txtHomeZip.setEnabled(true);
        txtHomePhoneNumber.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int workZipNew, homeZipNew,ageNew ;
          double heightNew;
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String age = txtAge.getText();
        String height = txtHeight.getText();
        
        String workStreet = txtWorkStreet.getText();
        String workUnit = txtWorkUnit.getText();
        String workCity = txtWorkCity.getText();
        String workState = txtWorkState.getText();
        String workZip = txtWorkZip.getText();
        String workPhone = txtWorkPhoneNumber.getText();
        
        String homeStreet = txtHomeStreet.getText();
        String homeUnit = txtHomeUnit.getText();
        String homeCity = txtHomeCity.getText();
        String homeState = txtHomeState.getText();
        String homeZip = txtHomeZip.getText();
        String homePhone = txtHomePhoneNumber.getText();
        
        if("".equals(firstName) || "".equals(lastName) ||"".equals(height)|| "".equals(age) 
                || "".equals(workStreet)||"".equals(workPhone) || "".equals(workUnit) || "".equals(workCity) || "".equals(workState) || "".equals(workZip) 
                || "".equals(homeStreet) ||"".equals(homePhone)|| "".equals(homeUnit) || "".equals(homeCity) || "".equals(homeState) || "".equals(homeZip)) {
            JOptionPane.showMessageDialog(null, "Please enter all the details!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            workZipNew = Integer.parseInt(workZip);
            if (workZipNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric zip code!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        try {
            homeZipNew = Integer.parseInt(homeZip);
            if (homeZipNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric zip code!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        
        try {
            ageNew = Integer.parseInt(age);
            if (ageNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a age!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        /*Parsing for height*/
       try {
          heightNew = Double.parseDouble(height);
            if (heightNew < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a numeric SSN!.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setAge(Integer.parseInt(txtAge.getText()));
        person.setHeight(Double.parseDouble(txtHeight.getText()));
               

        workAddress.setStreetAddress(workStreet);
        workAddress.setUnitNumber(workUnit);
        workAddress.setCity(workCity);
        workAddress.setState(workState);
        workAddress.setZip(workZipNew);
        workAddress.setPhoneNumber(Long.parseLong(workPhone));
        
        homeAddress.setStreetAddress(homeStreet);
        homeAddress.setUnitNumber(homeUnit);
        homeAddress.setCity(homeCity);
        homeAddress.setState(homeState);
        homeAddress.setZip(homeZipNew);
        homeAddress.setPhoneNumber(Long.parseLong(homePhone));
        
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtAge.setEnabled(false);
        
        txtWorkStreet.setEnabled(false);
        txtWorkUnit.setEnabled(false);
        txtWorkCity.setEnabled(false);
        txtWorkState.setEnabled(false);
        txtWorkZip.setEnabled(false);
        txtWorkPhoneNumber.setEnabled(false);

        txtHomeStreet.setEnabled(false);
        txtHomeUnit.setEnabled(false);
        txtHomeCity.setEnabled(false);
        txtHomeState.setEnabled(false);
        txtHomeZip.setEnabled(false);
        txtHomePhoneNumber.setEnabled(false);
            
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Account updated successfully!");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtWorkStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkStreetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeAddress;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomePhoneNumber;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeStreet;
    private javax.swing.JTextField txtHomeUnit;
    private javax.swing.JTextField txtHomeZip;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkPhoneNumber;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreet;
    private javax.swing.JTextField txtWorkUnit;
    private javax.swing.JTextField txtWorkZip;
    // End of variables declaration//GEN-END:variables
}
